title: obaid's longer thoughts
author: obaid
email: me@obaid.wtf
description: >-
  politics + systems + economics + markets + binary technologies + innovation + sciences + futbol + overton window/pop culture
  this is very prone to change as I add, drop more interests

baseurl: ""
url: "https://obaidregens.github.io"

# Build settings
remote_theme: riggraz/no-style-please

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Theme settings
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
